# Generated by Django 4.2.27 on 2026-01-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='bottle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='ingredient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
