# Generated by Django 5.2.8 on 2025-11-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BottleSlot",
            fields=[
                (
                    "bottle_number",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("liquid_name", models.CharField(default="Empty", max_length=200)),
            ],
            options={
                "ordering": ["bottle_number"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "recipe_name",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("bottle_1", models.PositiveIntegerField(default=0)),
                ("bottle_2", models.PositiveIntegerField(default=0)),
                ("bottle_3", models.PositiveIntegerField(default=0)),
                ("bottle_4", models.PositiveIntegerField(default=0)),
                ("bottle_5", models.PositiveIntegerField(default=0)),
                ("bottle_6", models.PositiveIntegerField(default=0)),
                ("bottle_7", models.PositiveIntegerField(default=0)),
                ("bottle_8", models.PositiveIntegerField(default=0)),
                ("bottle_9", models.PositiveIntegerField(default=0)),
                ("bottle_10", models.PositiveIntegerField(default=0)),
                ("bottle_11", models.PositiveIntegerField(default=0)),
                ("bottle_12", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
