# Generated by Django 5.2.8 on 2025-11-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_bottleslot_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="price",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="recipe",
            name="video_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
