# Generated by Django 5.2.8 on 2025-11-19 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_ingredient_recipeingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycount",
            name="recipe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.recipe",
            ),
        ),
    ]
