# Generated by Django 5.2.8 on 2025-11-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_dailycount_recipe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="bottle_1",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="bottle_10",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="bottle_11",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="bottle_12",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="bottle_2",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="bottle_3",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="bottle_4",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="bottle_5",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="bottle_6",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="bottle_7",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="bottle_8",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="bottle_9",
        ),
    ]
