# Generated by Django 5.2.8 on 2025-11-19 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_recipe_bottle_1_remove_recipe_bottle_10_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bottleslot",
            options={"ordering": ["machine", "bottle_number"]},
        ),
        migrations.AddField(
            model_name="bottleslot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="bottleslot",
            name="bottle_number",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "machine_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.owner",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bottleslot",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.machine",
            ),
        ),
        migrations.AddField(
            model_name="dailycount",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.machine",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bottleslot",
            unique_together={("machine", "bottle_number")},
        ),
    ]
